config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  

  get 'chirps/index'

  get 'chirps/new'

  get 'chirps/edit'

  get 'chirps/show'

  resources :chirps

  scope ':author', as: 'author' do
    resources :chirps, except: ['create', 'update', 'destroy']
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ApplicationRecord
  has_attached_file :pic, default_url: ""
  validates_attachment :pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  def index
    @chirps = Chirp.where(params.permit(:author))
  end

  def show
    @chirp = Chirp.find_by(params.permit(:author, :id))
  end

  def edit
    @chirp = Chirp.find_by(params.permit(:author, :id))
  end

  def new
    @chirp = Chirp.new(params.permit(:author))
  end

  def create
    @chirp = Chirp.new(params[:chirp].permit(:author, :body, :pic))
    if @chirp.save
      redirect_to chirp_path(@chirp)
    else
      render 'new'
    end
  end

  def update
    @chirp = Chirp.find(params[:id])
    if @chirp.update(params[:chirp].permit(:author, :body, :pic))
      redirect_to chirp_path(@chirp)
    else
      render 'edit'
    end
  end

  def destroy
    Chirp.find(params[:id]).destroy
    redirect_to chirps_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chirps/edit.html.erb
<h1>Edit this Chirp</h1>

<%= form_for @chirp do |f| %>
  <div>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.label :pic %>
    <%= f.file_field :pic %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>

<% end %>

app/views/chirps/index.html.erb
<h1>All Chirps</h1>
<p>
  <%= link_to 'Make a new Chirp', new_chirp_path %>
</p>
<hr>
<% @chirps.each do |chirp| %>
  <p>
    <%= chirp.body %>
  </p>

    <%= image_tag chirp.pic.url, width: '100' %>

  <p>
    - <i><%= link_to chirp.author, author_chirps_path(chirp.author) %></i>
  </p>

  <%= link_to 'Read More', chirp_path(chirp) %>
<br>
<br>
<br>
<hr>  

<% end %>

app/views/chirps/new.html.erb
<h1>Make a new Chirp!</h1>

<%= form_for @chirp do |f| %>
  <div>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.label :pic %>
    <%= f.file_field :pic %>
  </div>

  <div>
    <%= f.submit 'Chirp!' %>
  </div>

<% end -%>  

app/views/chirps/show.html.erb
<p>
  <%= @chirp.body %>
</p>
  <%= image_tag @chirp.pic.url, width: '100' %>
<p>
  -<i><%= @chirp.author %></i>
</p>

<br>
<%= link_to 'Edit this Chirp', edit_chirp_path %>
<%= link_to 'Delete this Chirp', chirp_path(@chirp), method: 'delete' %>
<%= link_to 'See all Chirps', chirps_path %>

app/views/home/index.html.erb
<h1>Welcome to Chirper</h1>
<p>Hit the button below to view all chirps and begin!</p>
<%= link_to 'Begin', chirps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chirper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>